# Generated by Django 4.1.1 on 2022-10-30 10:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.ImageAvatarStorage(), upload_to=accounts.models.avatar_path),
        ),
    ]
