# Generated by Django 4.1.1 on 2022-10-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
