# Generated by Django 4.1.2 on 2022-11-18 16:11

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_mobile_description_tablet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('ebook_reader', 'E-Book Reader')], default=None, max_length=15)),
                ('alias', models.CharField(max_length=210, unique=True)),
                ('product_number', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to=products.models.product_path)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('prize', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('display_size', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('internal_memory', models.PositiveIntegerField(default=0)),
                ('battery_capacity', models.PositiveIntegerField(default=0)),
                ('sim_number', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('touched_display', models.BinaryField(default=True)),
                ('mobile_standards', models.ManyToManyField(to='products.mobilestandard')),
                ('operation_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.operationsystem')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.producer')),
            ],
        ),
        migrations.CreateModel(
            name='SimType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedEbookFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.DeleteModel(
            name='Tablet',
        ),
        migrations.AddField(
            model_name='product',
            name='sim_type',
            field=models.ManyToManyField(to='products.simtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='supported_ebook_formats',
            field=models.ManyToManyField(blank=True, related_name='supported_ebook_formats', to='products.supportedebookformat'),
        ),
    ]
