# Generated by Django 4.1.2 on 2022-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_mobilestandard_operationsystem_producer_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simtype',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
