# Generated by Django 4.1.2 on 2022-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_simtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilestandard',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
