# Generated by Django 4.1.2 on 2022-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_mobilestandard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedebookformat',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
