# Generated by Django 4.1.2 on 2022-11-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_supportedebookformat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='touched_display',
            field=models.BooleanField(default=True),
        ),
    ]
