# Generated by Django 4.1.2 on 2022-11-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_end_date_published_product_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_number',
        ),
    ]
