# Generated by Django 4.1.2 on 2022-11-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_date_published',
        ),
    ]
