# Generated by Django 4.1.2 on 2022-11-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_end_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobile_standards',
            field=models.ManyToManyField(blank=True, to='products.mobilestandard'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sim_type',
            field=models.ManyToManyField(blank=True, to='products.simtype'),
        ),
    ]
